export type Category = 'Medical' | 'Security' | 'Fire' | 'General';
export type Incident = {id:string;title:string;type:Category;severity:string;location:string;status:string;created:number;assigned:string[];eta:number;caller:string;notes:string[];timeline:string[];outcome?:string;simulated?:boolean;simulationDue?:number;coordinates?:[number,number]};
export type ActivityEvent={title:string;detail:string;age:number;type:string;id?:string;created?:number;read?:boolean;incidentId?:string};
export type Responder = {id:string;name:string;role:Category;team:string;status:string;location:string;phone:string;battery:number;email?:string;accessCode?:string;organizationId?:string};
export const locations = ['Engineering Complex','Main Library','Student Hostel A','Student Hostel B','Medical Centre','Admin Centre','Sports Complex','Main Gate','Chapel','Cafeteria'];
// Stable initial timestamps keep server and browser HTML identical. The browser
// rebases a fresh demo session to the current time after hydration.
export const demoEpoch=Date.UTC(2025,8,10,20,14);
const now=demoEpoch;
export const initialIncidents:Incident[]=[
 {id:'AU-1042',title:'Medical Emergency',type:'Medical',severity:'Critical',location:'Engineering Complex',status:'En Route',created:now-120000,assigned:['R-014','R-005'],eta:3,caller:'Temiloluwa Adebayo · Student',notes:[],timeline:['Emergency request received','Medical team assigned','R-014 and R-005 en route']},
 {id:'AU-1041',title:'Security Incident',type:'Security',severity:'High',location:'Student Hostel B',status:'Assigned',created:now-360000,assigned:['R-004'],eta:4,caller:'Chidinma Okeke · Staff',notes:[],timeline:['Security concern reported','Dispatcher acknowledged','R-004 assigned']},
 ...Array.from({length:16},(_,i)=>({id:`AU-${1040-i}`,title:['First Aid Request','Access Check','Smoke Alarm','Welfare Check'][i%4],type:(['Medical','Security','Fire','General'] as Category[])[i%4],severity:'Standard',location:locations[(i+1)%locations.length],status:'Resolved',created:now-(i+1)*1800000,assigned:[`R-00${i%5+1}`],eta:0,caller:'Campus reception · Staff',notes:[],timeline:['Incident received','Responder dispatched','On scene','Incident closed'],outcome:i%5===0?'False alarm':'Assistance provided'}))
];
export const initialResponders:Responder[]=Array.from({length:14},(_,i)=>({id:`R-${String(i+1).padStart(3,'0')}`,name:['Adewale Bello','Chisom Okafor','Tunde Akinola','Fatima Ibrahim','Grace Adeyemi','David Afolabi','Amara Okonkwo','Daniel Musa','Zainab Yusuf','Samuel Ojo','Esther Balogun','Emmanuel John','Mary Nwosu','Oluwaseun James'][i],role:(['Medical','Security','Fire','Security','Medical'] as Category[])[i%5],team:['Medical Team','Security','Fire Safety','Security','Medical Team'][i%5],status:i===3||i===13?'En Route':i>10&&i<13?'Offline':i===2?'On Call':'Available',location:locations[i%locations.length],phone:`+234 803 555 ${String(1000+i)}`,battery:98-i*3,email:`responder${i+1}@adelekeuniversity.edu.ng`,accessCode:`RESP-AU-${String(i+1).padStart(3,'0')}`,organizationId:'org-adeleke'}));
export const initialActivity:ActivityEvent[]=[{title:'New medical alert received',detail:'Engineering Complex',age:2,type:'Medical',incidentId:'AU-1042'}, {title:'Responder (ID: R-014) en route',detail:'Engineering Complex',age:3,type:'Responder',incidentId:'AU-1042'}, {title:'Security alert assigned',detail:'Student Hostel B',age:5,type:'Security',incidentId:'AU-1041'}, {title:'Incident closed',detail:'Library (General)',age:12,type:'General'}, {title:'Responder back on duty',detail:'R-009',age:18,type:'General'}].map((e,i)=>({...e,id:`seed-${i}`,created:demoEpoch-e.age*60000,read:i>=3}));
export const chartData=[{time:'6AM',Medical:2,Security:0,Fire:0,General:0},{time:'9AM',Medical:4,Security:2,Fire:1,General:1},{time:'12PM',Medical:3.5,Security:5.5,Fire:2,General:1.5},{time:'3PM',Medical:2.5,Security:3,Fire:1,General:1.5},{time:'6PM',Medical:3,Security:4.5,Fire:1,General:1},{time:'9PM',Medical:2,Security:4.5,Fire:1,General:.5}];
