import { chromium } from '@playwright/test';
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const page = await browser.newPage({ viewport: { width: 1672, height: 941 }, deviceScaleFactor: 1 });
const errors=[];
page.on('pageerror', error=>errors.push(error.message));
await page.goto('http://127.0.0.1:3000/dashboard', {waitUntil:'networkidle',timeout:90000});
await page.locator('.leaflet-tile-loaded').first().waitFor({timeout:30000});
await page.screenshot({path:'artifacts/atlas-desktop.png',fullPage:true});
const dimensions=await page.evaluate(()=>({viewport:innerWidth,body:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,tiles:document.querySelectorAll('.leaflet-tile-loaded').length,main:document.querySelector('.overview-columns').getBoundingClientRect().toJSON()}));
console.log('Desktop:',JSON.stringify(dimensions));
await page.getByRole('link',{name:'Live Alerts'}).click();
await page.getByRole('button',{name:'Create alert',exact:true}).click();
await page.getByRole('textbox',{name:'Incident title'}).fill('Verification medical incident');
await page.getByRole('dialog').getByRole('button',{name:'Create alert',exact:true}).click();
await page.getByRole('heading',{name:'Verification medical incident'}).waitFor();
await page.getByRole('button',{name:'Assign responder',exact:true}).click();
await page.locator('.assignment-option').first().click();
await page.getByRole('textbox',{name:'Dispatcher note'}).fill('Responder confirmed on scene.');
await page.getByRole('button',{name:'Add note',exact:true}).click();
await page.getByText('Responder confirmed on scene.',{exact:true}).waitFor();
await page.getByRole('button',{name:'Mark resolved'}).click();
await page.getByRole('button',{name:'Confirm resolution'}).click();
console.log('Alert creation, assignment, note and resolution: passed');
await page.goto('http://127.0.0.1:3000/broadcast');
await page.getByRole('textbox',{name:'Title',exact:true}).fill('Campus all-clear notice');
await page.getByRole('textbox',{name:'Message',exact:true}).fill('The reported incident has been resolved. Normal campus activities can resume.');
await page.getByRole('button',{name:'Review broadcast'}).click();
await page.getByRole('button',{name:'Confirm and send'}).click();
await page.locator('.broadcast-record').getByText('Campus all-clear notice',{exact:true}).waitFor();
console.log('Broadcast confirmation and simulated delivery: passed');
await page.goto('http://127.0.0.1:3000/reports');
await page.getByRole('button',{name:'7 Days',exact:true}).click();
const download=page.waitForEvent('download');
await page.getByRole('button',{name:'Export CSV'}).click();
console.log('CSV download:',(await download).suggestedFilename());
await page.goto('http://127.0.0.1:3000/responders');
await page.getByRole('textbox',{name:'Search responders'}).fill('Adewale');
if(await page.locator('tbody tr').count()!==1)throw new Error('Responder search failed');
await page.getByRole('button',{name:'View profile',exact:true}).click();
await page.getByRole('button',{name:'Mark unavailable'}).click();
console.log('Responder search and availability: passed');
await page.evaluate(()=>localStorage.removeItem('atlas-command-v2'));
await page.goto('http://127.0.0.1:3000/dashboard');
await page.setViewportSize({width:1440,height:900});
await page.waitForTimeout(800);
await page.screenshot({path:'artifacts/atlas-1440.png',fullPage:true});
await page.setViewportSize({width:834,height:1112});
await page.waitForTimeout(500);
await page.screenshot({path:'artifacts/atlas-tablet.png',fullPage:true});
console.log('Tablet overflow:',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
console.log('Runtime errors:',JSON.stringify(errors));
await browser.close();
if(errors.length)process.exitCode=1;
